server {
    listen 80;
    server_name localhost;

    # Serve static files from /usr/share/nginx/html
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Try to serve files directly, fallback to index.html for SPA routing
        try_files $uri $uri/ =404;
    }

    # Proxy /api to test.domain.com
    location /api/ {
        proxy_pass https://traccar.tonbridge-scouts.org.uk/api/;
        proxy_set_header Host traccar.tonbridge-scouts.org.uk;
        proxy_ssl_name traccar.tonbridge-scouts.org.uk;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/socket/ {
        proxy_pass https://traccar.tonbridge-scouts.org.uk/api/socket/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host traccar.tonbridge-scouts.org.uk;
        proxy_ssl_server_name on;
        proxy_ssl_name traccar.tonbridge-scouts.org.uk;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}