on: [push]

name: Build & Push docker image to ACR

env:
  ACR_NAME: k8sdevaccessitoacr

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
          az acr login --name ${{ env.ACR_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
          docker buildx build --push \
          --platform linux/amd64,linux/arm64 \
          -f modern/Dockerfile \
          --tag ${{ env.ACR_NAME }}.azurecr.io/traccar:v1 \
          modern

    - name: Log out from Azure
      run: az logout
